### PR TITLE
ISSUE 3 Add .zprintrc support

### PR DESCRIPTION
**Pull request by tmattacchione**
**Whats up?**

Thank you @roman01la for putting `zprint-clj` and `zprint-atom` together.  This is great work!   As noted in #3, I too felt the need for the customization power of `.zprintrc`.  As a result, I put together an initial implementation to support this.  

**M'kay, tell me more**

This PR includes the following changes for your consideration:

- update the build scripts to build for node environments
- support for the `.zprintrc` file (the first point outlined in #3 )
- a local development guide for the README
- upgrade cljs from `1.9.x` -> `1.10.439`
- upgrade zprint from `0.4.6` -> `0.4.13`

The implementation to support the `.zprintrc` file follows the implementation set out by [zprint-npm](https://github.com/thheller/zprint-npm).  

I have tested this locally as a CLI app and also in Atom and it seems to work well.  

Any guidance  you have on this matter would be greatly appreciated.

### CODE REVIEW

**Comment by ash14** [comment]
Any updates on this? I've currently got this monkeypatched into my setup and it works quite well as is.

**Comment by roman01la** [comment]
@tkjone LGTM. The only thing is that how about looking up config file in project directory as well? I imagine this would be useful for OSS projects where authors might have their preferred config in the repo.

**Comment by tmattacchione** [comment]
@roman01la Good point!  Do you want me to add this as part of this PR or create a new one?  

What do you think about letting the user provide a path to find the config in general.  So the lookup could be something like:  

1. check if user passed a path to the config
2. look in local dir for config
3. look in global dir for config

**Comment by roman01la** [comment]
I think adding to this pr is fine. I'd go with local and global lookups for now, bc these are common options.

**Comment by tmattacchione** [comment]
@roman01la Okay, finally got around to implementing current directory (project level) `.zprintrc` lookup.  This is a naive approach and there are much better ones, but this should satisfy the base level 
requirement.  Let me know what you think.

**A few questions**

- Do we want to keep the output of `out/*` tracked in git?
- I bumped the `cljs` and `zprint` versions to latest.  Seems to run without issue.  Let me know if this was not what you had in mind and I can revert it.

Cheers!

**Comment by roman01la** [comment]
LGTM 👍

**Pull request merged**
